name: .NET Core Build

on:
#  push:
#    branches: [ "*" ]
#  pull_request:
#    branches: [ "main" ]
    
   workflow_dispatch:
     branch:
       - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0  # Imagen oficial de .NET SDK
    
    defaults:
      run:
        working-directory: temas/abstraccion/csharp/Code

        


    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run
      run: dotnet run
    - name: Test
      run: cd ../Test && dotnet test

