name: Run C# Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and Run Tests
      run: |
        cd temas/anotaciones/csharp-01/Tests_Anotaciones
        dotnet add package NUnit
        dotnet add package System.Text.Json
        dotnet test 