name: Anotaciones Java-02

on:
  workflow_dispatch:
    branches:
      - main  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        cd temas/anotaciones/java-02/logger
        mvn clean compile

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        cd temas/anotaciones/java-02/logger
        mvn clean compile

    - name: Run tests
      run: |
        cd temas/anotaciones/java-02/logger
        mvn test