name: Delegación en Ruby (Federico y Mauro)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        
    - name: Install dependencies
      run: |
        gem install bundler
        cd ./temas/delegacion/ruby-01
        bundle install
        
    - name: Run tests in specified directory
      run: |
        cd ./temas/delegacion/ruby-01/test
        ruby Clan_test.rb
        ruby Cocina_test.rb

  deploy:
    runs-on: ubuntu-latest
    
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        
    - name: Install dependencies
      run: |
        gem install bundler
        cd ./temas/delegacion/ruby-01
        bundle install
        
    - name: Run Ruby script
      run: |
        cd ./temas/delegacion/ruby-01/src
        ruby Clan.rb
        ruby Cocina.rb