name: Errores TypeScript

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependencias
      run: |
        cd temas/errores/typescript
        npm install

    - name: Build
      run: |
        cd temas/errores/typescript
        npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependencias
      run: |
        cd temas/errores/typescript
        npm install

    - name: Test
      run: |
        cd temas/errores/typescript
        npm run test