name: Run C# Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and Run Tests
      run: |
        cd temas/inyeccion/csharp-01/Tests_Inyeccion
        dotnet add package NUnit
        dotnet add package Moq
        dotnet add package NUnit3TestAdapter
        dotnet add package Microsoft.NET.Test.Sdk
        dotnet test 